services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command:
      ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory", "-cors", "*"]
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: unless-stopped
    networks:
      - app-network

volumes:
  dynamodb-data:
    driver: local

networks:
  app-network:
    driver: bridge
